openapi: "3.0.0"
info:
  title: API pour l'authentification des utilisateurs
  version: "1.0.0"
paths:
  /signup:
    post:
      summary: Inscription d'un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: Utilisateur créé avec succès
        '400':
          description: Requête invalide, l'utilisateur n'a pas pu être créé
        '500':
          description: Erreur interne du serveur
    parameters: []
  /login:
    post:
      summary: Connexion d'un utilisateur existant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Connexion réussie, renvoie un token JWT pour l'utilisateur
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  token:
                    type: string
        '401':
          description: Utilisateur ou mot de passe incorrect
        '500':
          description: Erreur interne du serveur
    parameters: []
